#include<iostream>
using namespace std;
int main(){
    int a=10, b=5;
    cout<<"operators in c++ are:"<<endl;
    cout<<"arithemetic operators"<<endl;
    cout<<"the value of a+b = "<<a+b<<endl;
    cout<<"the value of a-b = "<<a-b<<endl;
    cout<<"the value of a*b = "<<a*b<<endl;
    cout<<"the value of a/b = "<<a/b<<endl;
    cout<<"the value of a%b = "<<a%b<<endl;
    cout<<"the value of a++ = "<<a++<<endl;
    cout<<"the value of a-- = "<<a--<<endl;
    cout<<"the value of ++a = "<<++a<<endl;
    cout<<"the value of --a = "<<--a<<endl;
    /*assignment operators = used to assign the values to variable.
    int a=10,b=6
    char d='d'
    */
   cout<<"comparison operator"<<endl;
   cout<<"the value of a==b = "<<(a==b)<<endl;
   cout<<"the value of a!=b = "<<(a!=b)<<endl;
   cout<<"the value of a>=b = "<<(a>=b)<<endl;
   cout<<"the value of a<=b = "<<(a<=b)<<endl;
   cout<<"the value of a>b = "<<(a>b)<<endl;
   cout<<"the value of a<b = "<<(a<b)<<endl;
   cout<<"logical operators"<<endl;
   cout<<"the value of ((a==b) & (a<b)) = "<<((a==b) & (a<b))<<endl;
   cout<<"the value of ((a==b) || (a<b)) = "<<((a==b) || (a<b))<<endl;
   cout<<"the value of (!(a==b)) = "<<(!(a==b))<<endl;
}